# Prebuilt image with Chrome + Driver already installed
FROM selenium/standalone-chrome:latest

USER root

# Install Python & Selenium
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir selenium && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /apps

# Copy selenium script
COPY selenium_check.py .

# Run test
CMD ["python3", "selenium_check.py"]

